# Generated by Django 5.2.7 on 2025-10-29 13:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_club', models.CharField(max_length=200)),
                ('canchas_techo', models.IntegerField(default=0)),
                ('canchas_sin_techo', models.IntegerField(default=0)),
                ('es_techado', models.BooleanField(default=False)),
                ('tipo_superficie', models.CharField(choices=[('Vidrio/Sintetico', 'Vidrio/Sintético'), ('Pared/Sintetico', 'Pared/Sintético'), ('Pared/Piso Cemento', 'Pared/Piso Cemento')], max_length=20)),
                ('cant_profesores', models.IntegerField(default=0)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('valor_hora_ar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('Profesor_Admin', 'Profesor/Administrador'), ('Alumno_Usuario', 'Alumno/Usuario')], default='Alumno_Usuario', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('jugador_de', models.CharField(choices=[('Drive', 'Drive'), ('Revés', 'Revés')], default='Drive', max_length=10)),
                ('mano_habil', models.CharField(choices=[('Z', 'Zurdo'), ('D', 'Diestro')], default='D', max_length=1)),
                ('celular', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('nivel_categoria', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('confirmado', models.BooleanField(default=False)),
                ('notificado', models.BooleanField(default=False)),
                ('valor_ar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_profesor', models.ForeignKey(limit_choices_to={'rol': 'Profesor_Admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emparejamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('id_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padel_app.clase')),
                ('jugadores', models.ManyToManyField(limit_choices_to={'rol': 'Alumno_Usuario'}, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='padel_app.clase')),
                ('id_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padel_app.club')),
                ('id_emparejamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='padel_app.emparejamiento')),
                ('id_usuario', models.ForeignKey(limit_choices_to={'rol': 'Alumno_Usuario'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Confirmacion', 'Confirmación'), ('Cancelacion', 'Cancelación'), ('Recordatorio', 'Recordatorio')], max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('enviada', models.BooleanField(default=False)),
                ('id_clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='padel_app.clase')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
