# Generated by Django 5.2.7 on 2025-10-30 18:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_entreno', models.CharField(choices=[('Tecnica', 'Técnica'), ('Tactica', 'Táctica'), ('Fisico', 'Físico'), ('Estrategia', 'Estrategia'), ('Mixto', 'Mixto')], default='Mixto', max_length=20)),
                ('duracion_minutos', models.IntegerField(default=60)),
                ('nivel_minimo', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('nivel_maximo', models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='hora',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='entrenamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='padel_app.entrenamiento'),
        ),
    ]
